export const events = [
  {
    slug: "react-conf-2026",
    image: "/images/event1.png",
    title: "React Conf 2026",
    location: "San Francisco, CA",
     date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "nextjs-summit",
    image: "/images/event2.png",
    title: "Next.js Summit",
    location: "Austin, TX",
     date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "10:00 AM - 5:00 PM",
  },
  {
    slug: "javascript-world",
    image: "/images/event3.png",
    title: "JavaScript World Conference",
    location: "New York, NY",
     date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "8:30 AM - 7:00 PM",
  },
  {
    slug: "ai-hackathon",
    image: "/images/event4.png",
    title: "AI Innovation Hackathon",
    location: "Seattle, WA",
     date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "48 Hours",
  },
  {
    slug: "web3-developer-meetup",
    image: "/images/event5.png",
    title: "Web3 Developer Meetup",
    location: "Miami, FL",
     date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "6:00 PM - 9:00 PM",
  },
  {
    slug: "fullstack-conference",
    image: "/images/event6.png",
    title: "Full Stack Conference",
    location: "Denver, CO",
     date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "devops-unleashed",
    image: "/images/event1.png",
    title: "DevOps Unleashed",
    location: "Chicago, IL",
     date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "8:00 AM - 5:30 PM",
  },
  {
    slug: "mobile-dev-summit",
    image: "/images/event2.png",
    title: "Mobile Development Summit",
    location: "Los Angeles, CA",
     date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "9:30 AM - 6:00 PM",
  },
  {
    slug: "cybersecurity-conference",
    image: "/images/event3.png",
    title: "Cybersecurity Conference",
    location: "Boston, MA",
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "8:00 AM - 7:00 PM",
  },
  {
    slug: "data-science-hackathon",
    image: "/images/event4.png",
    title: "Data Science Hackathon",
    location: "San Diego, CA",
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "72 Hours",
  },
  {
    slug: "cloud-native-meetup",
    image: "/images/event5.png",
    title: "Cloud Native Meetup",
    location: "Portland, OR",
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "6:30 PM - 9:00 PM",
  },
  {
    slug: "frontend-masters",
    image: "/images/event6.png",
    title: "Frontend Masters Conference",
    location: "Nashville, TN",
     date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    time: "9:00 AM - 5:00 PM",
  },
];